export const PROFILE_SOURCES = [
  'Facebook (inzerát)',
  'Facebook (reklama)',
  'Profesia (inzerát)',
  'Profesia (databáza)',
  'Telegram (skupina)',
  'Viber (skupina)',
  'Google Business Profil',
  'Google (reklama)',
  'Referencie',
  'Web stránka',
  'Návšteva pobočky',
  'HR web portál',
  'Headhunting (priame oslovenie)',
  'Kariérne veľtrhy',
  'Školské a univerzitné partnerstvá',
  'Instagram ',
  'LinkedIn',
  'Externý dodávateľ',
];
